# Generated by Django 4.1.3 on 2022-11-05 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersdata",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="usersdata",
            name="surname",
        ),
    ]
