# Generated by Django 4.1.3 on 2022-11-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_usersdata_firstname_remove_usersdata_surname"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersdata",
            name="firstname",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="usersdata",
            name="surname",
            field=models.CharField(default="", max_length=255),
        ),
    ]
