# Generated by Django 4.1.3 on 2022-11-05 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_usersdata_firstname_usersdata_surname"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersdata",
            name="search_area",
            field=models.IntegerField(
                default=300,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reports",
            name="current_people",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999),
                ],
            ),
        ),
    ]
